"""all User attributes now not nullable

Revision ID: 11f679d935b4
Revises: aecc659dd100
Create Date: 2024-07-11 13:14:51.047574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f679d935b4'
down_revision = 'aecc659dd100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
