"""added nullable to instructions

Revision ID: 4b640fb399d5
Revises: c3a6c930bf04
Create Date: 2024-07-09 18:02:25.805361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b640fb399d5'
down_revision = 'c3a6c930bf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
